### PR TITLE
Sending cdi version with requests

### PR DESCRIPTION
**Pull request by porcellus**
The library should send the CDI version it uses with each request to make sure that it uses a version both support.

### CODE REVIEW

**Comment by porcellus** [comment]
I added sorting to `SupportedApiVersions` because the code below depends on it being in descending order, and it seems too easy to make a mistake and have them in ascending order. 
Of course, I'm happy to move this into a comment if that's your preference or into `GetApiVersionAsync` itself.

**Review by seniorquico — APPROVED** [review]

**Comment by seniorquico** [comment]
Looks fine to me. To be honest, I started to rethink the structure of the API client after having started to use it and the complexity of needing the CDI version. I had brainstormed a refactor where the CDI version becomes an internal implementation detail of the API client, and then the method signatures drop the explicit CDI version argument. (Essentially, push this whole API version container concept into the API client.) I couldn't really brainstorm a reason why a caller would want to explicitly choose an older/different CDI version, and moving it inside would make using the API client _much_ simpler (wouldn't have to access the API version container and the API client, could just simply depend on the API client). I believe I started to experiment with some of this on my wip branch. Let me know if this is interesting, and maybe this conversation could shift over to a GitHub issue for further development or refinement.

**Comment by porcellus** [comment]
Moving the APIContainer into the API client is a great idea; I just didn't want to change the structure too much.

**Comment by seniorquico** [comment]
No worries. A refactor like that would be a _much_ bigger change. This at least gets the correct API client behavior implemented!

**Pull request merged**
